<script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
function check_submit()
{
    var submit = true;
    //validation might be done - sex must be chosen, login must have more than 5 characters, 
    //passwords must be the same, every field mustn't be empty
    $("#errors").html("");
}
</script>
<p>Rejestracja:</p>
<div style="width: 50%">
<form method="post" action="" id="register_form">
    <div class="form-group">
    <label for="login">Login:</label>
    <input type="text" name="login" id="login" class="form-control" />
    </div>
    <div class="form-group">
    <label for="password">Hasło:</label>
    <input type="password" name="password" id="password" class="form-control" /><br />
    <label for="password2">Powtórz hasło:</label>
    <input type="password" name="password2" id="password2" class="form-control" />
    </div>
    <div class="form-group">
    <label for="first_name">Imię:</label>
    <input type="text" name="first_name" id="first_name" class="form-control" />
    </div>
    <div class="form-group">
    <label for="last_name">Nawisko:</label>
    <input type="text" name="last_name" id="last_name" class="form-control" />
    </div>
    <div class="form-group">
    <label for="sex">Płeć:</label>
    <select name="sex" id="sex" class="form-control">
            <option value="x">wybierz</option>
            <option value="K">kobieta</option>
            <option value="M">mężczyzna</option>
    </select>
    </div>
    <button class="btn btn-primary">Zatwierdź</button>
</form>
</div>
<div style="background-color: red; color: white" id="errors">
<?php if (isset($_SESSION['error_messages']) ) {
    foreach($_SESSION['error_messages'] as $message) {
        echo '<p>'.$message.'</p>';
    }
} ?>
</div>
