<script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
function check_submit()
{
    var submit = true;
    $("#errors").html("");
}
</script>
<p>Rejestracja:</p>
<form method="post" action="" id="register_form">
    Login: <input type="text" name="login" id="login" /><br />
    Hasło: <input type="password" name="password" id="password" /><br />
    Powtórz hasło: <input type="password" name="password2" id="password2" /><br />
    Imię: <input type="text" name="first_name" id="first_name" /><br />
    Nawisko: <input type="text" name="last_name" id="last_name" /><br />
    Płeć: <select name="sex" id="sex">
            <option value="x">wybierz</option>
            <option value="K">kobieta</option>
            <option value="M">mężczyzna</option>
    </select>
    <button>Zatwierdź</button>
</form>
<div style="background-color: red; color: white" id="errors"></div>
